name: BanknotesPlus
version: ${project.version}
main: me.itswagpvp.banknotesplus.BanknotesPlus
api-version: 1.13
authors: [ _ItsWagPvP ]
softdepend:
  - NBTAPI
  - EconomyPlus
commands:
  banknotesplus:
    aliases: 
      - bnp
    usage: /<command>
  withdraw:
    usage: /<command> amount
  deposit:
    usage: /<command>